fn foo() {}

// ERRORS
// NO_MAIN_FUNCTION:1:1